language: python

sudo: required

dist: xenial

services:
  - docker

stages:
  - build
  - test
  - publish

env:
  global:
    - SALT_VER="" # latest
  matrix:
    - DOCKER_IMAGE=debian-stretch
#    - DOCKER_IMAGE=ubuntu-xenial
#    - DOCKER_IMAGE=ubuntu-bionic
#    - DOCKER_IMAGE=fedora-30

#matrix:
#  fast_finish: true
#  allow_failures: # only unstable distro-based tests are allowed to fail
#    - env: DOCKER_IMAGE=debian-sid

jobs:
  include:
    - stage: build
      name: "Build"
      script: .travis/prepare.sh
      env: DOCKER_IMAGE=debian-stretch
      before_cache:
        - >
          mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
          | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
    #    - env: DOCKER_IMAGE=debian-sid
#      script: .travis/prepare.sh
#    - env: DOCKER_IMAGE=ubuntu-xenial
#      script: .travis/prepare.sh
#    - env: DOCKER_IMAGE=ubuntu-bionic
#      script: .travis/prepare.sh
#    - env: DOCKER_IMAGE=fedora-30
#      script: .travis/prepare.sh
    - stage: test
      name: "Test"
      before_install:
        - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
      script: .travis/test.sh
      # will contain all of the env by default of test stage definition
    - stage: publish
      name: "Publish"
      env: DOCKER_IMAGE=debian-stretch
      script: .travis/publish.sh
#    - env: DOCKER_IMAGE=ubuntu-bionic
#      script: .travis/publish.sh
    - stage: cleanup
      name: "Clean cache"
      env: DOCKER_IMAGE=debian-stretch
      before_cache:
        - >
          rm -rf $HOME/docker
# cleanup of docker images in some final stage
# docker images are not shared between stages: how to
# https://github.com/travis-ci/travis-ci/issues/5358
# https://travis-ci.org/s12v/sns/builds/161873445

cache:
  bundler: true
  directories:
    - $HOME/docker
