language: python

sudo: required

dist: xenial

services:
  - docker

stages:
  - test

env:
  global:
    - SALT_VER="" # latest
  matrix:
    - DOCKER_IMAGE=debian-stretch
    - DOCKER_IMAGE=ubuntu-xenial
    - DOCKER_IMAGE=ubuntu-bionic
    - DOCKER_IMAGE=fedora-30

matrix:
  fast_finish: true
  allow_failures: # only unstable distro-based tests are allowed to fail
    - env: DOCKER_IMAGE=debian-sid

jobs:
  include:
    - stage: test
      name: "Test"
      before_install: .travis/prepare.sh
      script: .travis/test.sh
      after_success: .travis/publish.sh

#cache:
#  bundler: true
#  directories:
#    - $HOME/docker
