language: python

sudo: required

dist: xenial

services:
  - docker

stages:
  - test

env:
  global:
    - SALT_VER="" # latest

jobs:
  include:
    - stage: test
      name: "Test and publish"
      env:
        - DOCKER_IMAGE=debian-stretch
      before_install: .travis/prepare.sh
      script: .travis/test.sh
      after_success: .travis/publish.sh
    - env:
      - DOCKER_IMAGE=ubuntu-xenial
      before_install: .travis/prepare.sh
      script: .travis/test.sh
    - env:
        - DOCKER_IMAGE=ubuntu-bionic
      before_install: .travis/prepare.sh
      script: .travis/test.sh
      after_success: .travis/publish.sh
    - env:
        - DOCKER_IMAGE=fedora-30
      before_install: .travis/prepare.sh
      script: .travis/test.sh
