language: python

sudo: required

dist: trusty

services:
  - docker

env:
  global:
    - SALT_VER="" # latest
  matrix:
    - DOCKER_IMAGE=debian-sid
      TEST_CASE=salt-masterless-dry
    - DOCKER_IMAGE=debian-jessie
      TEST_CASE=salt-masterless-dry
    - DOCKER_IMAGE=debian-stretch
      TEST_CASE=salt-masterless-dry
    - DOCKER_IMAGE=ubuntu-xenial
      TEST_CASE=salt-masterless-dry
    - DOCKER_IMAGE=ubuntu-artful
      TEST_CASE=salt-masterless-dry

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker build --build-arg=SALT_VER=$SALT_VER -t "$DOCKER_IMAGE" -f .travis/"$DOCKER_IMAGE"/dry/Dockerfile .

script:
  - docker run --privileged "$DOCKER_IMAGE"
