language: python

sudo: required

dist: xenial

services:
  - docker

env:
  global:
    - SALT_VER="" # latest
    - ENVOY_TAG="latest"
  matrix:
    - DOCKER_IMAGE=debian-sid
    - DOCKER_IMAGE=debian-stretch
    - DOCKER_IMAGE=ubuntu-xenial
    - DOCKER_IMAGE=ubuntu-bionic
    - DOCKER_IMAGE=fedora-29

matrix:
  fast_finish: true
  allow_failures: # only unstable distro-based tests are allowed to fail
    - env: DOCKER_IMAGE=debian-sid

before_install: .travis/prepare.sh

script: .travis/test.sh

after_success: .travis/publish.sh

# there is little or no benefit of using build stages as they don't share docker images
