language: python

sudo: required

dist: xenial

services:
  - docker

stages:
  - build
  - test
  - publish

env:
  global:
    - SALT_VER="" # latest
  matrix:
    - DOCKER_IMAGE=debian-sid
    - DOCKER_IMAGE=debian-stretch
    - DOCKER_IMAGE=ubuntu-xenial
    - DOCKER_IMAGE=ubuntu-bionic
    - DOCKER_IMAGE=fedora-30

matrix:
  fast_finish: true
  allow_failures: # only unstable distro-based tests are allowed to fail
    - env: DOCKER_IMAGE=debian-sid

jobs:
  include:
    - stage: build
      script:
        - echo "build"
    - stage: test
      script:
        - echo "test"

after_success:
  - echo "after success"

# there is little or no benefit of using build stages as they don't share docker images
