apiVersion: v1
clusters:
{%- for c in kubeconfig %}
  - cluster:
      certificate-authority-data: {{ salt.hashutil.base64_encodefile(c.ca_cert) }}
      server: {{ c.server }}
    name: {{ c.cluster }}
{%- endfor %}
contexts:
{%- for c in kubeconfig %}
  - context:
      cluster: {{ c.cluster }}
      user: {{ c.user }}
    name: {{ c.cluster }}
{%- endfor %}
current-context: {{ kubeconfig|map(attribute='cluster')|first }}
kind: Config
preferences: {}
users:
{%- for c in kubeconfig %}
  - name: {{ c.user }}
    user:
      client-certificate-data: {{ salt.hashutil.base64_encodefile(c.client_cert) }}
      client-key-data: {{ salt.hashutil.base64_encodefile(c.client_key) }}
{%- endfor %}
